### ISSUE TITLE
Error during boot-up

### ISSUE THREAD

**Issue by lukefullard** [whitphx/stlite#1136]
Recently I have been getting this error during boot up:

`Error during booting up
Traceback (most recent call last):
  File "/lib/python3.12/site-packages/micropip/_commands/install.py", line 142, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 55, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 68, in add_requirement
    await self.add_wheel(wheel, extras=set(), specifier="")
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 236, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 55, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 59, in add_requirement
    return await self.add_requirement_inner(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 141, in add_requirement_inner
    satisfied, ver = self.check_version_satisfied(req)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 86, in check_version_satisfied
    raise ValueError(
ValueError: Requested 'tenacity<9,>=8.1.0', but tenacity==9.0.0 is already installed`

My only packages imported were:
plotly
openpyxl

This was using https://edit.share.stlite.net/.
Can provide code if useful.
Thanks

**Comment by lukefullard** [comment]
I should also add the error is gone if I simply refresh the page...

**Comment by whitphx** [comment]
Thank you! I also encountered this error randomly, but now I think the latest ver. of Streamlit/Stlite updated the `tenacity` dependency version so this error should be gone.
Let me close this issue atm, and plz reopen it if you find this error again. Thanks!
