### ISSUE TITLE
@stlite/mountable does not work in some envs as the worker cannot be created

### ISSUE THREAD

**Issue by whitphx** [whitphx/stlite#136]
For example, when using `@stlite/mountable` from a static site served at `localhost:8000`, the following error occurs.
```
worker.js:2 Uncaught DOMException: Failed to construct 'Worker': Script at 'https://whitphx.github.io/stlite/lib/mountable/stlite.worker.js' cannot be accessed from origin 'http://localhost:8000'.
    at new c (https://whitphx.github.io/stlite/lib/mountable/stlite.js:2:597729)
    at new e (https://whitphx.github.io/stlite/lib/mountable/stlite.js:2:598088)
    at Module.nc (https://whitphx.github.io/stlite/lib/mountable/stlite.js:2:4060619)
    at http://localhost:8000/:14:12
```

In this repo, #130 caused this problem where `worker-loader` has been introduced.
This is explained at https://v4.webpack.js.org/loaders/worker-loader/#cross-origin-policy

**Comment by whitphx** [comment]
The `inline` option of `worker-loader` may solve? https://v4.webpack.js.org/loaders/worker-loader/
