### ISSUE TITLE
entry point not found

### ISSUE THREAD

**Issue by hoishing** [whitphx/stlite#990]
when I try to use entry point other then `streamlit_app.py`, I got `FileNotFoundError`, seems the entry-point is hard-coded

my script

```js
stlite.mount(
  {
    entry_point: "main.py",
    files: {
      "main.py": {
        url: "./main.py",
      },
    },
  },
  document.getElementById("root")
);
```

Error message:

Traceback (most recent call last): File "/lib/python3.12/site-packages/stlite_server/server.py", line 103, in start_websocket self._websocket_handler.open(on_message) File "/lib/python3.12/site-packages/stlite_server/server.py", line 243, in open self._session_id = self._runtime.connect_session( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "streamlit/runtime/runtime.py", line 386, in connect_session File "streamlit/runtime/websocket_session_manager.py", line 97, in connect_session File "streamlit/runtime/app_session.py", line 147, in __init__ File "streamlit/runtime/app_session.py", line 184, in register_file_watchers File "streamlit/watcher/local_sources_watcher.py", line 58, in __init__ File "streamlit/watcher/local_sources_watcher.py", line 67, in update_watched_pages File "streamlit/watcher/local_sources_watcher.py", line 122, in _register_watcher File "streamlit/watcher/polling_path_watcher.py", line 70, in __init__ File "streamlit/watcher/util.py", line 84, in path_modification_time FileNotFoundError: [Errno 44] No such file or directory: '/home/pyodide/streamlit_app.py'

**Comment by whitphx** [comment]
Hi, the option name is `entrypoint`, not `entry_point`.
However falling back to the default value `streamlit_app.py` as you wrote is confusing so that behavior will be fixed in #991 .
Thanks.
